name: 'Stale issue handler'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
    
jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: read|write|none
      
    steps:
      - uses: actions/stale@main
        id: stale
        with:
          stale-issue-message: 'This issue is stale because it has been open 1 day with no activity.'
          days-before-issue-stale: 1
          days-before-issue-close: 2
      - name: Print outputs
        run: echo ${{ join(steps.stale.outputs.*, ',') }}
